name: my_device
description: Agile and easy access to device information and internet connection alerts
version: 0.2.1
homepage: https://github.com/misdevelop-org/my_device

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #

